services:
  db:
    image: postgres:16-alpine
    container_name: controle-gastos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controle_gastos
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # garante que os dados do postgres persistam entre reinicializações do container